// opcode, txType, prior
// priors from JavaScript https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
const opsList = [
    ['(', 'TxBrackets', 21],
    ['.', 'TxBinOp', 20],
    ['[', 'TxIndex', 20],
    ['new', 'TxUnOp', 20],
    ['call', 'TxFnCall', 20],
    ['?.', 'TxBinOp', 20],
    ['#++', 'TxPostfix', 18],
    ['#--', 'TxPostfix', 18],
    ['...', 'TxUnOp', 17], // Такого оператора нет, но ...
    ['!', 'TxUnOp', 17],
    ['~', 'TxUnOp', 17],
    ['neg', 'TxUnOp', 17],
    ['++', 'TxUnOp', 17],
    ['--', 'TxUnOp', 17],
    ['typeof', 'TxUnOp', 17],
    ['delete', 'TxUnOp', 17],
    ['await', 'TxUnOp', 17],
    ['**', 'TxBinOp', 16],
    ['*', 'TxBinOp', 15],
    ['/', 'TxBinOp', 15],
    ['%', 'TxBinOp', 15],
    ['+', 'TxBinOp', 14],
    ['-', 'TxBinOp', 14],
    ['<<', 'TxBinOp', 13],
    ['>>', 'TxBinOp', 13],
    ['>>>', 'TxBinOp', 13],
    ['<', 'TxBinOp', 12],
    ['<=', 'TxBinOp', 12],
    ['>', 'TxBinOp', 12],
    ['>=', 'TxBinOp', 12],
    ['in', 'TxBinOp', 12],
    ['instanceof', 'TxBinOp', 12],
    ['==', 'TxBinOp', 11],
    ['!=', 'TxBinOp', 11],
    ['===', 'TxBinOp', 11],
    ['!==', 'TxBinOp', 11],
    ['&', 'TxBinOp', 10],
    ['^', 'TxBinOp', 9],
    ['|', 'TxBinOp', 8],
    ['&&', 'TxBinOp', 7],
    ['||', 'TxBinOp', 6],
    ['??', 'TxBinOp', 5],
    ['?', 'TxTernOp', 4],
    ['=', 'TxBinOp', 3],
    ['+=', 'TxBinOp', 3],
    ['-=', 'TxBinOp', 3],
    ['*=', 'TxBinOp', 3],
    ['/=', 'TxBinOp', 3],
    ['%=', 'TxBinOp', 3],
    ['**=', 'TxBinOp', 3],
    ['<<=', 'TxBinOp', 3],
    ['>>=', 'TxBinOp', 3],
    ['&=', 'TxBinOp', 3],
    ['^=', 'TxBinOp', 3],
    ['|=', 'TxBinOp', 3],
]

const opcodeMap = new Map(opsList.map(i => [i[0], i]))

module.exports = {
    opsList,
    opcodeMap,
}